rm_manual:
  robot_type: "standard"
  chassis:
    topic: "/cmd_chassis"
    accel_x: 10.0
    accel_y: 10.0
    accel_z: 20.0
    safety_power: 50.0
    capacitor_threshold: 0.1
    charge_power: 0
    extra_power: 5000
    burst_power: 500
  vel:
    topic: "/cmd_vel"
    max_linear_x: 4.0
    max_linear_y: 4.0
    max_angular_z: 10.0
  gimbal:
    topic: "/cmd_gimbal"
    max_yaw_vel: 12.56
    max_pitch_vel: 8.37
    target_cost_function:
      k_pos: 1.0
      k_vel: 1.0
      k_hp: 1.0
      k_freq: 1.0
      timeout: 0.05
  shooter:
    topic: "/cmd_shoot"
    gimbal_error_limit: 0.05
    heat_limit:
      expect_shoot_frequency: 10
      safe_shoot_frequency: 10
      heat_coeff: 1.5
      safety_speed: 15.0
      type: "ID1_17MM"
  controllers_list:
    - controllers/robot_state_controller
    - controllers/joint_state_controller
    - controllers/chassis_controller
  state_controllers_switch:
    start_controllers:
      - controllers/robot_state_controller
      - controllers/joint_state_controller
  base_controllers_switch:
    start_controllers:
      - controllers/chassis_controller
      - controllers/gimbal_controller
      - controllers/shooter_controller
  calibration_manager:

