rm_manual:
  robot_type: "engineer"
  chassis:
    topic: "/cmd_chassis"
    accel_x: 4.0
    accel_y: 4.0
    accel_z: 5.0
    safety_power: 50.0
    capacitor_threshold: 0.1
    charge_power: 0
    extra_power: 5000
    burst_power: 500
  vel:
    topic: "/cmd_vel"
    max_linear_x: 4.0
    max_linear_y: 4.0
    max_angular_z: 6.0
  gimbal:
    topic: "/cmd_gimbal"
    max_yaw_vel: 12.56
    max_pitch_vel: 8.37
    target_cost_function:
      k_pos: 1.0
      k_vel: 1.0
      k_hp: 1.0
      k_freq: 1.0
      timeout: 0.05
  mast:
    topic: "/controllers/mast_controller/command"
    open_pos: 0.
    close_pos: 0.
  card:
    topic: "/controllers/card_controller/command"
    open_pos: 0.
    close_pos: 0.1
  controllers_list:
    state_controllers:
      - controllers/robot_state_controller
      - controllers/joint_state_controller
    main_controllers:
      - controllers/chassis_controller
      - controllers/arm_trajectory_controller
      - controllers/mast_controller
      - controllers/card_controller
      - controllers/hand_controller
    calibration_controllers:
      - controllers/mast_calibration_controller
      - controllers/joint5_calibration_controller
      - controllers/joint4_calibration_controller
      - controllers/joint3_calibration_controller
      - controllers/joint2_calibration_controller
      - controllers/joint1_calibration_controller
      - controllers/hand_calibration_controller
      - controllers/card_calibration_controller
  power_on_calibration:
    - start_controller: controllers/mast_calibration_controller
      stop_controller: controllers/mast_controller
      service_name: /controllers/mast_calibration_controller/is_calibrated
    - start_controller: controllers/card_calibration_controller
      stop_controller: controllers/card_controller
      service_name: /controllers/card_calibration_controller/is_calibrated
  arm_calibration:
    - start_controller: controllers/joint1_calibration_controller
      stop_controller: controllers/arm_trajectory_controller
      service_name: /controllers/joint1_calibration_controller/is_calibrated
    - start_controller: controllers/joint2_calibration_controller
      stop_controller: controllers/arm_trajectory_controller
      service_name: /controllers/joint2_calibration_controller/is_calibrated
    - start_controller: controllers/joint3_calibration_controller
      stop_controller: controllers/arm_trajectory_controller
      service_name: /controllers/joint3_calibration_controller/is_calibrated
    - start_controller: controllers/joint4_calibration_controller
      stop_controller: controllers/arm_trajectory_controller
      service_name: /controllers/joint4_calibration_controller/is_calibrated
    - start_controller: controllers/joint5_calibration_controller
      stop_controller: controllers/arm_trajectory_controller
      service_name: /controllers/joint5_calibration_controller/is_calibrated
    - start_controller: controllers/hand_calibration_controller
      stop_controller: controllers/hand_controller
      service_name: /controllers/hand_calibration_controller/is_calibrated
  ui:
    warning:
      - { name: "spin", data: { type: "string", id: 10, start_x: 900, start_y: 750, start_angle: 15, width: 2, color: "yellow", content: "please spin!!", delay: 1.2 } }
      - { name: "calibration", data: { type: "string", id: 11, start_x: 900, start_y: 700, start_angle: 15, width: 2, color: "yellow", content: "please calibrate!!", delay: 1.2 } }
