rm_manual:
  robot_type: "hero"
  chassis:
    topic: "/cmd_chassis"
    accel_x: 7
    accel_y: 10.0
    accel_z: 20
    safety_power: 50.0
    capacitor_threshold: 0.1
    charge_power: 20
    extra_power: 30
    burst_power: 220
  vel:
    topic: "/cmd_vel"
    max_linear_x: 4.0
    max_linear_y: 4.0
    max_angular_z: 10.0
    gyro_move_reduction: 0.5
  gimbal:
    topic: "/cmd_gimbal"
    max_yaw_vel: 12.56
    max_pitch_vel: 8.37
    track_timeout: 0.5
    target_cost_function:
      k_pos: 1.0
      k_vel: 0.0
      k_hp: 0.0
      k_freq: 99.0
      timeout: 0.1
  shooter:
    topic: "/cmd_shoot"
    gimbal_error_limit: 0.05
    heat_limit:
      expect_shoot_frequency_1: 1
      expect_shoot_frequency_2: 2
      expect_shoot_frequency_3: 3
      burst_shoot_frequency: 5
      safe_shoot_frequency: 1
      heat_coeff: 3.0
      type: "ID1_42MM"
  cover:
    topic: "/controllers/cover_controller/command"
    open_pos: -2.0
    close_pos: 0.0
  detection_switch:
    fail_limit: 10

  controllers_list:
    state_controllers:
      - controllers/robot_state_controller
      - controllers/joint_state_controller
    main_controllers:
      - controllers/chassis_controller
      - controllers/gimbal_controller
      - controllers/shooter_controller
    calibration_controllers:
      - controllers/trigger_calibration_controller

  trigger_calibration:
    - start_controller: controllers/trigger_calibration_controller
      stop_controller: controllers/shooter_controller
      service_name: /controllers/trigger_calibration_controller/is_calibrated

  ui:
    trigger_change:
      - name: "chassis"
        config: { start_position: [ 400, 750 ], size: 15, width: 2, title: "chassis:" }
      - name: "target"
        config: { start_position: [ 400, 700 ], size: 15, width: 2, title: "target: " }
    time_change:
      - name: "capacitor"
        config: { start_position: [ 900, 100 ], size: 15, width: 2, delay: 0.5 }
    fixed:
      - name: "3m"
        config: { type: "line", width: 7, color: "yellow",
                  start_position: [ [ 900, 600 ], [ 900, 600 ] ],
                  end_position: [ [ 1020, 600 ], [ 1020, 600 ] ] }
      - name: "4m"
        config: { type: "line", width: 5, color: "yellow",
                  start_position: [ [ 910,550 ], [ 910, 550 ] ],
                  end_position: [ [ 1010,550 ], [ 1010, 550 ] ] }
      - name: "5m"
        config: { type: "line", width: 3, color: "yellow",
                  start_position: [ [ 920, 500 ], [ 920, 500 ] ],
                  end_position: [ [ 1000, 500 ], [ 1000, 500 ] ] }
      - name: "mid"
        config: { type: "line", width: 3, color: "yellow",
                  start_position: [ 960, 500 ], end_position: [ 960, 600 ] }
    flash:
      - name: "spin"
        config: { start_position: [ 900, 750 ], size: 15, width: 2,
                  color: "yellow", content: "please spin!!", delay: 1.2 }
      - name: "armor0"
        config: { type: "circle", width: 3, radius: 50, color: "yellow", delay: 0.75 }
      - name: "armor1"
        config: { type: "circle", width: 3, radius: 50, color: "yellow", delay: 0.75 }
      - name: "armor2"
        config: { type: "circle", width: 3, radius: 50, color: "yellow", delay: 0.75 }
      - name: "armor3"
        config: { type: "circle", width: 3, radius: 50, color: "yellow", delay: 0.75 }
