rm_manual:
  robot_type: "hero"
  chassis:
    topic: "/cmd_chassis"
    accel_x: 10.0
    accel_y: 10.0
    accel_z: 5.0
    safety_power: 50.0
    capacitor_threshold: 0.1
    charge_power: 20
    extra_power: 30
    burst_power: 220
  vel:
    topic: "/cmd_vel"
    max_linear_x: 4.0
    max_linear_y: 4.0
    max_angular_z: 10.0
  gimbal:
    topic: "/cmd_gimbal"
    max_yaw_vel: 12.56
    max_pitch_vel: 8.37
    track_timeout: 0.5
    target_cost_function:
      k_pos: 1.0
      k_vel: 0.0
      k_hp: 0.0
      k_freq: 99.0
      timeout: 0.1
  shooter:
    topic: "/cmd_shoot"
    gimbal_error_limit: 0.05
    heat_limit:
      expect_shoot_frequency_1: 1
      expect_shoot_frequency_2: 2
      expect_shoot_frequency_3: 3
      burst_shoot_frequency: 5
      safe_shoot_frequency: 1
      heat_coeff: 3.0
      type: "ID1_42MM"
  cover:
    topic: "/controllers/cover_controller/command"
    open_pos: -2.0
    close_pos: 0.0
  enemy_color_switch:
    error_amount_limit: 10
  controllers_list:
    - controllers/robot_state_controller
    - controllers/joint_state_controller
    - controllers/chassis_controller
    - controllers/gimbal_controller
    - controllers/shooter_controller
    - controllers/trigger_calibration_controller
    - controllers/orientation_controller
  state_controllers_switch:
    start_controllers:
      - controllers/robot_state_controller
      - controllers/joint_state_controller
      - controllers/orientation_controller
  base_controllers_switch:
    start_controllers:
      - controllers/chassis_controller
      - controllers/gimbal_controller
  calibration_manager:
    trigger:
      switch:
        start_controllers:
          - controllers/trigger_calibration_controller
        stop_controllers:
          - controllers/shooter_controller
      query:
        service_name: /controllers/trigger_calibration_controller/is_calibrated
  ui:
    title:
      - { name: "chassis", data: { type: "string", id: 0, start_x: 150, start_y: 800, end_x: 0, end_y: 0, start_angle: 0, end_angle: 0, radius: 0, width: 3, color: "white", content: "chassis:" } }
      - { name: "gimbal", data: { type: "string", id: 1, start_x: 150, start_y: 750, end_x: 0, end_y: 0, start_angle: 0, end_angle: 0, radius: 0, width: 3, color: "white", content: "gimbal:" } }
      - { name: "shooter", data: { type: "string", id: 2, start_x: 150, start_y: 700, end_x: 0, end_y: 0, start_angle: 0, end_angle: 0, radius: 0, width: 3, color: "white", content: "shooter:" } }
      - { name: "target", data: { type: "string", id: 3, start_x: 150, start_y: 650, end_x: 0, end_y: 0, start_angle: 0, end_angle: 0, radius: 0, width: 3, color: "white", content: "target:" } }
    warning:
      - { name: "spin", data: { type: "string", id: 4, start_x: 900, start_y: 700, end_x: 0, end_y: 0, start_angle: 0, end_angle: 0, radius: 0, width: 3, color: "yellow", content: "please spin!!" } }
    capacitor:
      - { name: "capacitor", data: { type: "string", id: 6, start_x: 900, start_y: 100, end_x: 0, end_y: 0, start_angle: 0, end_angle: 0, radius: 0, width: 3, color: "yellow", content: "" } }
    state:
      - { name: "chassis", data: { type: "string", id: 7, start_x: 200, start_y: 800, end_x: 0, end_y: 0, start_angle: 0, end_angle: 0, radius: 0, width: 3, color: "yellow", content: "" } }
      - { name: "gimbal", data: { type: "string", id: 8, start_x: 200, start_y: 750, end_x: 0, end_y: 0, start_angle: 0, end_angle: 0, radius: 0, width: 3, color: "yellow", content: "" } }
      - { name: "shooter", data: { type: "string", id: 9, start_x: 200, start_y: 700, end_x: 0, end_y: 0, start_angle: 0, end_angle: 0, radius: 0, width: 3, color: "yellow", content: "" } }
      - { name: "target", data: { type: "string", id: 10, start_x: 200, start_y: 650, end_x: 0, end_y: 0, start_angle: 0, end_angle: 0, radius: 0, width: 3, color: "yellow", content: "" } }

