rm_manual:
  robot_type: "hero"
  controller_manager:
    information_controllers:
      - controllers/robot_state_controller
      - controllers/joint_state_controller
      - controllers/imu_sensor_controller
    movement_controllers:
      - controllers/chassis_controller
      - controllers/gimbal_controller
      - controllers/shooter_controller
  chassis:
    topic: "cmd_chassis"
    accel_x: 10.0
    accel_y: 10.0
    accel_w: 6.0
    safety_power: 50.0
  vel:
    topic: "cmd_vel"
    max_vel_x: 4.0
    max_vel_y: 4.0
    max_vel_w: 5.0
  gimbal:
    topic: "cmd_gimbal"
    max_yaw_vel: 12.56
    max_pitch_vel: 12.56
    target_cost_function:
      k_pos: 1.0
      k_vel: 1.0
      k_hp: 1.0
      k_freq: 1.0
      timeout: 0.05
  shooter:
    topic: "cmd_shoot"
    gimbal_error_limit: 0.05
    heat_limit:
      expect_shoot_frequency: 10
      safe_shoot_frequency: 10
      heat_coeff: 1.0
      type: "ID1_42MM"

