rm_manual:
  robot_type: "hero"
  chassis:
    topic: "/cmd_chassis"
    accel_x: 10.0
    accel_y: 10.0
    accel_z: 5.0
    safety_power: 50.0
    capacitor_threshold: 0.1
    charge_power: 20
    extra_power: 30
    burst_power: 220
  vel:
    topic: "/cmd_vel"
    max_linear_x: 4.0
    max_linear_y: 4.0
    max_angular_z: 10.0
  gimbal:
    topic: "/cmd_gimbal"
    max_yaw_vel: 12.56
    max_pitch_vel: 8.37
    track_timeout: 0.5
    target_cost_function:
      k_pos: 1.0
      k_vel: 0.0
      k_hp: 0.0
      k_freq: 99.0
      timeout: 0.1
  shooter:
    topic: "/cmd_shoot"
    gimbal_error_limit: 0.05
    heat_limit:
      expect_shoot_frequency_1: 1
      expect_shoot_frequency_2: 2
      expect_shoot_frequency_3: 3
      burst_shoot_frequency: 5
      safe_shoot_frequency: 1
      heat_coeff: 3.0
      type: "ID1_42MM"
  cover:
    topic: "/controllers/cover_controller/command"
    open_pos: -2.0
    close_pos: 0.0
  detection_switch:
    fail_limit: 10

  controllers_list:
    state_controllers:
      - controllers/robot_state_controller
      - controllers/joint_state_controller
    main_controllers:
      - controllers/chassis_controller
      - controllers/gimbal_controller
      - controllers/shooter_controller
    calibration_controllers:
      - controllers/trigger_calibration_controller

  trigger_calibration:
    - start_controller: controllers/trigger_calibration_controller
      stop_controller: controllers/shooter_controller
      service_name: /controllers/trigger_calibration_controller/is_calibrated

  ui:
    state:
      - { name: "chassis", data: { type: "string", id: 0, start_x: 400, start_y: 800, start_angle: 15, width: 3, title: "chassis:" } }
      - { name: "target", data: { type: "string", id: 3,  start_x: 400, start_y: 650, start_angle: 15, width: 3, title: "target: " } }
    aim:
      - { name: "3m", data: { type: "line", id: 7, start_x: [ 920,920,920,920 ], start_y: [ 500,500,500,500 ], end_x: [ 1000,1000,1000,1000 ], end_y: [ 500,500,500,500 ], width: 3, color: "pink" } }
      - { name: "4m", data: { type: "line", id: 8, start_x: [ 910,910,910,910 ], start_y: [ 525,525,525,525 ], end_x: [ 1010,1010,1010,1010 ], end_y: [ 525,525,525,525 ], width: 3, color: "pink" } }
      - { name: "5m", data: { type: "line", id: 9, start_x: [ 900,900,900,900 ], start_y: [ 550,550,550,550 ], end_x: [ 1020,1020,1020,1020 ], end_y: [ 550,550,550,550 ], width: 3, color: "pink" } }
    capacitor:
      - { name: "capacitor", data: { type: "string", id: 6, start_x: 900, start_y: 100, start_angle: 15, width: 3 } }
