rm_manual:
  robot_type: "standard"
  chassis:
    topic: "/controllers/chassis_controller/command"
    accel_x: 10.0
    accel_y: 10.0
    accel_z: 20.0
    safety_power: 50.0
    capacitor_threshold: 0.1
    charge_power: 20
    extra_power: 30
    burst_power: 200
  vel:
    topic: "/cmd_vel"
    max_linear_x: 4.0
    max_linear_y: 4.0
    max_angular_z: 8.0
    gyro_move_reduction: 0.3
  gimbal:
    topic: "/controllers/gimbal_controller/command"
    max_yaw_vel: 12.56
    max_pitch_vel: 8.37
    track_timeout: 0.5
    target_cost_function:
      k_pos: 1.0
      k_vel: 1.0
      k_hp: 1.0
      k_freq: 1.0
      timeout: 0.05
  shooter:
    topic: "/controllers/shooter_controller/command"
    gimbal_error_limit: 0.05
    heat_limit:
      expect_shoot_frequency_1: 10
      expect_shoot_frequency_2: 15
      expect_shoot_frequency_3: 20
      burst_shoot_frequency: 20
      safe_shoot_frequency: 5
      heat_coeff: 8.0
      type: "ID1_17MM"
  cover:
    topic: "/controllers/cover_controller/command"
    on_pos: -2.0
    off_pos: 0.0
  detection_switch:
    fail_limit: 10
    service_name: "/detection_nodelet/status_switch"

  controllers_list:
    state_controllers:
      - controllers/robot_state_controller
      - controllers/joint_state_controller
      - controllers/imu_filter_controller
    main_controllers:
      - controllers/chassis_controller
      - controllers/orientation_controller
      - controllers/gimbal_controller
      - controllers/shooter_controller
      - controllers/cover_controller
    calibration_controllers:
      - controllers/trigger_calibration_controller
      - controllers/cover_calibration_controller

  cover_calibration:
    - start_controller: controllers/cover_calibration_controller
      stop_controller: controllers/cover_controller
      service_name: /controllers/cover_calibration_controller/is_calibrated
  trigger_calibration:
    - start_controller: controllers/trigger_calibration_controller
      stop_controller: controllers/shooter_controller
      service_name: /controllers/trigger_calibration_controller/is_calibrated

controllers:
  cover_controller:
    type: effort_controllers/JointPositionController
    joint: "cover_joint"
    pid: { p: 15.0, i: 0.0, d: 1.2, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true, publish_state: true }